# Базовая конфигурация для Code Telescope

# Настройки сканирования файловой системы
filesystem:
  # Шаблоны для включения файлов
  include_patterns:
    - "*.go"
    - "*.js"
    - "*.ts"
    - "*.py"
    - "*.java"
    - "*.c"
    - "*.cpp"
    - "*.h"
    - "*.hpp"
  # Шаблоны для исключения файлов
  exclude_patterns:
    - "*_test.go"
    - "test_*.py"
    - "**/test/**"
    - "**/node_modules/**"
    - "**/vendor/**"
    - "**/dist/**"
    - "**/build/**"
  # Максимальная глубина рекурсивного сканирования
  max_depth: 10

# Настройки парсера кода
parser:
  # Парсить приватные методы (начинающиеся с _)
  parse_private_methods: false
  # Максимальный размер файла для парсинга (в байтах)
  max_file_size: 1048576  # 1MB

# Настройки ЛЛМ
llm:
  # Провайдер ЛЛМ (openai, anthropic)
  provider: "openai"
  # Модель ЛЛМ
  model: "gpt-4"
  # Температура генерации
  temperature: 0.3
  # Максимальное количество токенов для генерации
  max_tokens: 1000
  # Максимальное количество запросов в пакете
  batch_size: 5
  # Пауза между пакетами запросов (в секундах)
  batch_delay: 1

# Настройки генерации Markdown
markdown:
  # Включать содержание
  include_toc: true
  # Включать информацию о файле (размер, дата изменения)
  include_file_info: true
  # Максимальная длина описания метода
  max_method_description_length: 200
  # Группировать методы по типам
  group_methods_by_type: true
  # Форматирование кода в документации
  code_style: "github"